### ISSUE TITLE
Debian package todo list

### ISSUE THREAD

**Issue by philclifford** [wimpysworld/deb-get#616]
A little collection of "failures" from the debian 11 marathon.  

Some (e.g. nala/nala-legacy) the test fails but deb-get is working fine 
Most just need filtering out or persuading upstream to build for debian

- [x] battery-monitor depends on gir1.2-appindicator3-0.1 #678
- [x] Beersmith -   packaged with zstd compression #633 
- [ ] teamviewer barfs
- [ ] system-monitoring-center misses version - maybe missing existing fix
- [x] stremio misses dependency :     Depends: libfdk-aac1 (>= 0.1.5) but it is not installable #678 
- [ ] opera-stable hangs : does not respect non-interactive and waits on user input forever asking for permission to add an apt list ... Needs to be skipped from CI testing or tested differently
- [x] openrgb #628
- [ ] nala not supported on pre-sid :  test should maybe try to pass correct non-installation identification 
- [ ] minigalaxy depends on unrar :   and installing unrar-free does not satisfy the dependency
- [ ] docker-desktop depends on docker-ce
- [ ] deborah
- [ ] quickobs
- [ ] Bitwarden purge errors - should possibly be handled better
- [ ] Bitwig dependencies not met

```

    The following packages have unmet dependencies:
     bitwig-studio : Depends: zlib1g:i386 but it is not installable
                     Depends: libx11-xcb1:i386 but it is not installable
                     Depends: libx11-6:i386 but it is not installable
                     Depends: libxau6:i386 but it is not installable
                     Depends: libxdmcp6:i386 but it is not installable
                     Depends: libxrender1:i386 but it is not installable
                     Depends: libfontconfig1:i386 but it is not installable
                     Depends: libxcb-icccm4:i386 but it is not installable
                     Depends: libxcb-util1:i386 but it is not installable
                     Depends: libxcb-shm0:i386 but it is not installable
                     Depends: libxcb-xinput0:i386 but it is not installable
                     Depends: libxkbcommon0:i386 but it is not installable
                     Depends: libxkbcommon-x11-0:i386 but it is not installable
                     Depends: libpixman-1-0:i386 but it is not installable
                     Depends: libcairo2:i386 but it is not installable
```

**Comment by philclifford** [comment]
I think this has gone as far as is useful in this issue.  We have separate issues for some remaining debian improvements, and have or will have focussed issues around improving behaviours and testing so I'm closing this one.
